name: fitness_app_capstone
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.2
  http: ^1.3.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cupertino_icons: ^1.0.8
  syncfusion_flutter_charts: ^29.1.35
  intl: ^0.20.2
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.0.15
  pedometer: ^4.1.0
  permission_handler: ^12.0.0+1
  cloud_firestore: ^5.0.0
  collection: any

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/AppIcon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: images/AppIcon.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.5


flutter:
  uses-material-design: true

  assets:
    - images/Exercise Background Image.png
    - images/Bench Press.png
    - images/Push-ups.png
    - images/Squats.png
    - images/Jumping Jacks.png
    - images/Running.png
    - images/Cycling Cardio.png
    - images/Light Jogging.png
    - images/Running Cardio.png
    - images/HIIT.png
    - images/Yoga.png
    - images/Dips.png
    - images/Burpees.png
    - images/Bicep Curls.png
    - images/Lunges.png
    - images/Walking.png
    - images/Basic Yoga.png
    - images/Deadlifts.png
    - images/Cycling.png
    - images/Crunches.png
    - images/Leg Raises.png
    - images/Plank.png
    - images/Mountain Climbers.png
    - images/Pull-ups.png
    - images/Pistol Squats.png
    - images/Pilates.png
    - images/Bodyweight Circuit.png
    - images/Swimming.png
    - images/AppIcon.png
