name: fitness_app_capstone
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.2
  http: ^1.3.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cupertino_icons: ^1.0.8
  syncfusion_flutter_charts: ^29.1.35
  intl: ^0.18.0
  lottie: ^3.3.1
  google_fonts: ^5.0.0
  shared_preferences: ^2.0.15
  pedometer: ^4.1.0
  permission_handler: ^11.0.0


  collection: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img.png
    - assets/cup.png
    - images/Exercise Background Image.webp
    - images/Bench Press.webp
    - images/Push-ups.webp
    - images/Squats.webp
    - images/Jumping Jacks.webp
    - images/Running.webp
    - images/Cycling Cardio.webp
    - images/Light Jogging.webp
    - images/Running Cardio.webp
    - images/HIIT.webp
    - images/Yoga.webp
    - images/Dips.webp
    - images/Burpees.webp
    - images/Bicep Curls.webp
    - images/Lunges.webp
    - images/Walking.webp
    - images/Basic Yoga.webp
    - images/Deadlifts.webp
    - images/Cycling.webp
    - images/Crunches.webp
    - images/Leg Raises.webp
    - images/Plank.webp
    - images/Mountain Climbers.webp
    - images/Pull-ups.webp
    - images/Pistol Squats.webp
    - images/Pilates.webp
    - images/Bodyweight Circuit.webp
    - images/Swimming.webp
