// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA07I9BNDNTrQB-T3lJZxfk0FaRd2cis_Y',
    appId: '1:502129494418:web:263f941e032527a81a994b',
    messagingSenderId: '502129494418',
    projectId: 'fitness-tracker-fd9b4',
    authDomain: 'fitness-tracker-fd9b4.firebaseapp.com',
    databaseURL: 'https://fitness-tracker-fd9b4-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-tracker-fd9b4.firebasestorage.app',
    measurementId: 'G-YMS9JBV0JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6G_V5d_aHu2KMdg747z_bl4qsv40lUQg',
    appId: '1:502129494418:android:22798fcae57c49941a994b',
    messagingSenderId: '502129494418',
    projectId: 'fitness-tracker-fd9b4',
    databaseURL: 'https://fitness-tracker-fd9b4-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-tracker-fd9b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq-kal0sWoYxVrnzfMeKS19ew_HujjTMI',
    appId: '1:502129494418:ios:25fadd120b0b441a1a994b',
    messagingSenderId: '502129494418',
    projectId: 'fitness-tracker-fd9b4',
    databaseURL: 'https://fitness-tracker-fd9b4-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-tracker-fd9b4.firebasestorage.app',
    iosBundleId: 'com.example.fitnessAppCapstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq-kal0sWoYxVrnzfMeKS19ew_HujjTMI',
    appId: '1:502129494418:ios:25fadd120b0b441a1a994b',
    messagingSenderId: '502129494418',
    projectId: 'fitness-tracker-fd9b4',
    databaseURL: 'https://fitness-tracker-fd9b4-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-tracker-fd9b4.firebasestorage.app',
    iosBundleId: 'com.example.fitnessAppCapstone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA07I9BNDNTrQB-T3lJZxfk0FaRd2cis_Y',
    appId: '1:502129494418:web:5d11d19c0ab4f18d1a994b',
    messagingSenderId: '502129494418',
    projectId: 'fitness-tracker-fd9b4',
    authDomain: 'fitness-tracker-fd9b4.firebaseapp.com',
    databaseURL: 'https://fitness-tracker-fd9b4-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-tracker-fd9b4.firebasestorage.app',
    measurementId: 'G-2QDWRK5YH8',
  );
}
